<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

<script>
	var WEB_SITE_NAME = `${WEB_SITE_NAME}`;
	var PROJECT_NAME = `${PROJECT_NAME}`;
	var CONTROLLER = `${CONTROLLER}`;
	var COMMAND = `${COMMAND}`;
	var OPEN_HOME_PAGE = `${OPEN_HOME_PAGE}`;
	var ADD_NEW_ALIEN = `${ADD_NEW_ALIEN}`;
	var ALIEN_NAME = `${ALIEN_NAME}`;
	var ALIEN_SMALL_DESCRIPTION = `${ALIEN_SMALL_DESCRIPTION}`;
	var ALIEN_FULL_DESCRIPTION = `${ALIEN_FULL_DESCRIPTION}`;
	var ALIEN_NEW_IMAGE = `${ALIEN_NEW_IMAGE}`;
	var BAN_USER = `${BAN_USER}`;
	var DAYS_TO_BAN = `${DAYS_TO_BAN}`;
	var UNBAN_USER = `${UNBAN_USER}`;
	var DEMOTE_ADMIN = `${DEMOTE_ADMIN}`;
	var PROMOTE_USER = `${PROMOTE_USER}`;
	var UPDATE_USER_EMAIL = `${UPDATE_USER_EMAIL}`;
	var LOGIN = `${LOGIN}`;
	var NEW_LOGIN = `${NEW_LOGIN}`;
	var PASSWORD = `${PASSWORD}`;
	var PASSWORD_CONFIRM = `${PASSWORD_CONFIRM}`;
	var NEW_IMAGE = `${NEW_IMAGE}`;
	var EMAIL = `${EMAIL}`;
	var NEW_EMAIL = `${NEW_EMAIL}`;
	var USER_ID = `${USER_ID}`;
	var UPDATE_USER_LOGIN = `${UPDATE_USER_LOGIN}`;
	var UPDATE_USER_PASSWORD = `${UPDATE_USER_PASSWORD}`;
	var UPDATE_USER_IMAGE = `${UPDATE_USER_IMAGE}`;

	// users form
	var UPDATE_STANDARD_EMAIL_FEEDBACK = `${UPDATE_STANDARD_EMAIL_FEEDBACK}`;
	var UPDATE_EMAIL_RESULT_INFO_STATUS = `${UPDATE_EMAIL_RESULT_INFO_STATUS}`;
	var UPDATE_EMAIL_RESULT_INFO_EMAIL_FEEDBACK = `${UPDATE_EMAIL_RESULT_INFO_EMAIL_FEEDBACK}`;

	var UPDATE_LOGIN_STANDARD_LOGIN_FEEDBACK = `${UPDATE_LOGIN_STANDARD_LOGIN_FEEDBACK}`;
	var UPDATE_LOGIN_RESULT_INFO_STATUS = `${UPDATE_LOGIN_RESULT_INFO_STATUS}`;
	var UPDATE_LOGIN_RESULT_INFO_LOGIN_FEEDBACK = `${UPDATE_LOGIN_RESULT_INFO_LOGIN_FEEDBACK}`;	

	var UPDATE_PASSWORD_STANDARD_PASSWORD_FEEDBACK = `${UPDATE_PASSWORD_STANDARD_PASSWORD_FEEDBACK}`;
	var UPDATE_PASSWORD_STANDARD_PASSWORD_CONFIRMATION_FEEDBACK = `${UPDATE_PASSWORD_STANDARD_PASSWORD_CONFIRMATION_FEEDBACK}`;
	var UPDATE_PASSWORD_RESULT_INFO_PASSWORD_STATUS = `${UPDATE_PASSWORD_RESULT_INFO_PASSWORD_STATUS}`;
	var UPDATE_PASSWORD_RESULT_INFO_PASSWORD_FEEDBACK = `${UPDATE_PASSWORD_RESULT_INFO_PASSWORD_FEEDBACK}`;
	var UPDATE_PASSWORD_RESULT_INFO_PASSWORD_CONFIRMATION_STATUS = `${UPDATE_PASSWORD_RESULT_INFO_PASSWORD_CONFIRMATION_STATUS}`;
	var UPDATE_PASSWORD_RESULT_INFO_PASSWORD_CONFIRMATION_FEEDBACK = `${UPDATE_PASSWORD_RESULT_INFO_PASSWORD_CONFIRMATION_FEEDBACK}`;
	var UPDATE_PASSWORD_RESULT_INFO_FEEDBACK_INVALID_PASSWORDS_NOT_EQUALS = `${UPDATE_PASSWORD_RESULT_INFO_FEEDBACK_INVALID_PASSWORDS_NOT_EQUALS}`;

	var UPDATE_IMAGE_STANDARD_IMAGE_FEEDBACK = `${UPDATE_IMAGE_STANDARD_IMAGE_FEEDBACK}`;
	var UPDATE_IMAGE_RESULT_INFO_FEEDBACK_INVALID_IMAGE = `${UPDATE_IMAGE_RESULT_INFO_FEEDBACK_INVALID_IMAGE}`;
	var UPDATE_IMAGE_RESULT_INFO_IMAGE_STATUS = `${UPDATE_IMAGE_RESULT_INFO_IMAGE_STATUS}`;
	var UPDATE_IMAGE_RESULT_INFO_IMAGE_FEEDBACK = `${UPDATE_IMAGE_RESULT_INFO_IMAGE_FEEDBACK}`;

	var BAN_UNBAN_USER_LOGIN_STATUS = `${BAN_UNBAN_USER_LOGIN_STATUS}`;
	var BAN_UNBAN_USER_DAYS_TO_BAN_STATUS = `${BAN_UNBAN_USER_DAYS_TO_BAN_STATUS}`;
	var BAN_UNBAN_USER_RESULT_INFO_LOGIN_FEEDBACK = `${BAN_UNBAN_USER_RESULT_INFO_LOGIN_FEEDBACK}`;
	var BAN_UNBAN_USER_RESULT_INFO_DAYS_TO_BAN_FEEDBACK = `${BAN_UNBAN_USER_RESULT_INFO_DAYS_TO_BAN_FEEDBACK}`;
	var BAN_UNBAN_USER_STANDARD_LOGIN_FEEDBACK = `${BAN_UNBAN_USER_STANDARD_LOGIN_FEEDBACK}`;
	var BAN_UNBAN_USER_STANDARD_DAYS_TO_BAN_FEEDBACK = `${BAN_UNBAN_USER_STANDARD_DAYS_TO_BAN_FEEDBACK}`;

	var PROMOTE_DEMOTE_USER_LOGIN_STATUS = `${PROMOTE_DEMOTE_USER_LOGIN_STATUS}`;
	var PROMOTE_DEMOTE_USER_RESULT_INFO_LOGIN_FEEDBACK = `${PROMOTE_DEMOTE_USER_RESULT_INFO_LOGIN_FEEDBACK}`;
	var PROMOTE_DEMOTE_USER_STANDARD_LOGIN_FEEDBACK = `${PROMOTE_DEMOTE_USER_STANDARD_LOGIN_FEEDBACK}`;

	var ADD_NEW_UPDATE_ALIEN_STANDARD_ALIEN_NAME_FEEDBACK = `${ADD_NEW_UPDATE_ALIEN_STANDARD_ALIEN_NAME_FEEDBACK}`;
	var ADD_NEW_UPDATE_ALIEN_STANDARD_ALIEN_SMALL_DESCRIPTION_FEEDBACK = `${ADD_NEW_UPDATE_ALIEN_STANDARD_ALIEN_SMALL_DESCRIPTION_FEEDBACK}`;
	var ADD_NEW_UPDATE_ALIEN_STANDARD_ALIEN_FULL_DESCRIPTION_FEEDBACK = `${ADD_NEW_UPDATE_ALIEN_STANDARD_ALIEN_FULL_DESCRIPTION_FEEDBACK}`;
	var ADD_NEW_UPDATE_ALIEN_STANDARD_ALIEN_IMAGE_FEEDBACK = `${ADD_NEW_UPDATE_ALIEN_STANDARD_ALIEN_IMAGE_FEEDBACK}`;
	var ADD_NEW_UPDATE_ALIEN_ALIEN_NAME_STATUS = `${ADD_NEW_UPDATE_ALIEN_ALIEN_NAME_STATUS}`;
	var ADD_NEW_UPDATE_ALIEN_ALIEN_SMALL_DESCRIPTION_STATUS = `${ADD_NEW_UPDATE_ALIEN_ALIEN_SMALL_DESCRIPTION_STATUS}`;
	var ADD_NEW_UPDATE_ALIEN_ALIEN_FULL_DESCRIPTION_STATUS = `${ADD_NEW_UPDATE_ALIEN_ALIEN_FULL_DESCRIPTION_STATUS}`;
	var ADD_NEW_UPDATE_ALIEN_ALIEN_IMAGE_STATUS = `${ADD_NEW_UPDATE_ALIEN_ALIEN_IMAGE_STATUS}`;
	var ADD_NEW_UPDATE_ALIEN_RESULT_INFO_ALIEN_NAME_FEEDBACK = `${ADD_NEW_UPDATE_ALIEN_RESULT_INFO_ALIEN_NAME_FEEDBACK}`;
	var ADD_NEW_UPDATE_ALIEN_RESULT_INFO_ALIEN_SMALL_DESCRIPTION_FEEDBACK = `${ADD_NEW_UPDATE_ALIEN_RESULT_INFO_ALIEN_SMALL_DESCRIPTION_FEEDBACK}`;
	var ADD_NEW_UPDATE_ALIEN_RESULT_INFO_ALIEN_FULL_DESCRIPTION_FEEDBACK = `${ADD_NEW_UPDATE_ALIEN_RESULT_INFO_ALIEN_FULL_DESCRIPTION_FEEDBACK}`;
	var ADD_NEW_UPDATE_ALIEN_RESULT_INFO_ALIEN_IMAGE_FEEDBACK = `${ADD_NEW_UPDATE_ALIEN_RESULT_INFO_ALIEN_IMAGE_FEEDBACK}`;
	
</script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js'></script>
<script type="text/javascript" src="<c:url value='${JS_USER_PROFILE}'/>"></script>
<script type="text/javascript" src="<c:url value='${JS_ADMIN_PROFILE}'/>"></script>
<h1>${TEXT[TEMPLATE_ADMIN_PROFILE]}</h1>
<div class="content-section">
	<div class="media">
		<jsp:include page="${TEMPLATE_USER_IMAGE_JSP}"/>
		<div class="media-body">
			<h2 id="user-profile-account-login" class="account-heading">${currentUser.login}</h2>
			<p id="user-profile-account-email" class="text-secondary">${currentUser.email}</p>
		</div>
	</div>
	<jsp:include page="${FORM_ALIEN_CREATE_JSP}"/>
	<jsp:include page="${FORM_BAN_UNBAN_USER_JSP}"/>
	<jsp:include page="${FORM_PROMOTE_DEMOTE_JSP}"/>
	<jsp:include page="${FORM_UPDATE_EMAIL_JSP}"/>
	<jsp:include page="${FORM_UPDATE_LOGIN_JSP}"/>
	<jsp:include page="${FORM_UPDATE_IMAGE_JSP}"/>
	<jsp:include page="${FORM_UPDATE_PASSWORD_JSP}"/>
</div>
