<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js'></script>
<script>
	var WEB_SITE_NAME = `${WEB_SITE_NAME}`;
	var PROJECT_NAME = `${PROJECT_NAME}`;
	var CONTROLLER = `${CONTROLLER}`;
	var COMMAND = `${COMMAND}`;
	var LOAD_EMAIL_UPDATE_FORM = `${LOAD_EMAIL_UPDATE_FORM}`;
	var LOAD_IMAGE_UPDATE_FORM = `${LOAD_IMAGE_UPDATE_FORM}`;
	var LOAD_USER_IMAGE = `${LOAD_USER_IMAGE}`;
	var LOAD_PASSWORD_UPDATE_FORM = `${LOAD_PASSWORD_UPDATE_FORM}`;
	var LOAD_LOGIN_UPDATE_FORM = `${LOAD_LOGIN_UPDATE_FORM}`;
	var LOGIN = `${LOGIN}`;
	var NEW_LOGIN = `${NEW_LOGIN}`;
	var PASSWORD = `${PASSWORD}`;
	var PASSWORD_CONFIRM = `${PASSWORD_CONFIRM}`;
	var NEW_IMAGE = `${NEW_IMAGE}`;
	var EMAIL = `${EMAIL}`;
	var NEW_EMAIL = `${NEW_EMAIL}`;
	var USER_ID = `${USER_ID}`;
	var userId = `${currentUser.id}`;
	var userLogin = `${currentUser.login}`;
	var userEmail = `${currentUser.email}`;
	var UPDATE_USER_EMAIL = `${UPDATE_USER_EMAIL}`;
	var UPDATE_USER_LOGIN = `${UPDATE_USER_LOGIN}`;
	var UPDATE_USER_PASSWORD = `${UPDATE_USER_PASSWORD}`;
	var UPDATE_USER_IMAGE = `${UPDATE_USER_IMAGE}`;

	// users form
	var UPDATE_STANDARD_EMAIL_FEEDBACK = `${UPDATE_STANDARD_EMAIL_FEEDBACK}`;
	var UPDATE_EMAIL_RESULT_INFO_STATUS = `${UPDATE_EMAIL_RESULT_INFO_STATUS}`;
	var UPDATE_EMAIL_RESULT_INFO_EMAIL_FEEDBACK = `${UPDATE_EMAIL_RESULT_INFO_EMAIL_FEEDBACK}`;
	
	var UPDATE_LOGIN_STANDARD_LOGIN_FEEDBACK = `${UPDATE_LOGIN_STANDARD_LOGIN_FEEDBACK}`;
	var UPDATE_LOGIN_RESULT_INFO_STATUS = `${UPDATE_LOGIN_RESULT_INFO_STATUS}`;
	var UPDATE_LOGIN_RESULT_INFO_LOGIN_FEEDBACK = `${UPDATE_LOGIN_RESULT_INFO_LOGIN_FEEDBACK}`;	


	var UPDATE_PASSWORD_STANDARD_PASSWORD_FEEDBACK = `${UPDATE_PASSWORD_STANDARD_PASSWORD_FEEDBACK}`;
	var UPDATE_PASSWORD_STANDARD_PASSWORD_CONFIRMATION_FEEDBACK = `${UPDATE_PASSWORD_STANDARD_PASSWORD_CONFIRMATION_FEEDBACK}`;
	var UPDATE_PASSWORD_RESULT_INFO_PASSWORD_STATUS = `${UPDATE_PASSWORD_RESULT_INFO_PASSWORD_STATUS}`;
	var UPDATE_PASSWORD_RESULT_INFO_PASSWORD_FEEDBACK = `${UPDATE_PASSWORD_RESULT_INFO_PASSWORD_FEEDBACK}`;
	var UPDATE_PASSWORD_RESULT_INFO_PASSWORD_CONFIRMATION_STATUS = `${UPDATE_PASSWORD_RESULT_INFO_PASSWORD_CONFIRMATION_STATUS}`;
	var UPDATE_PASSWORD_RESULT_INFO_PASSWORD_CONFIRMATION_FEEDBACK = `${UPDATE_PASSWORD_RESULT_INFO_PASSWORD_CONFIRMATION_FEEDBACK}`;


	var UPDATE_IMAGE_STANDARD_IMAGE_FEEDBACK = `${UPDATE_IMAGE_STANDARD_IMAGE_FEEDBACK}`;
	var UPDATE_IMAGE_RESULT_INFO_FEEDBACK_INVALID_IMAGE = `${UPDATE_IMAGE_RESULT_INFO_FEEDBACK_INVALID_IMAGE}`;
	var UPDATE_IMAGE_RESULT_INFO_IMAGE_STATUS = `${UPDATE_IMAGE_RESULT_INFO_IMAGE_STATUS}`;
	var UPDATE_IMAGE_RESULT_INFO_IMAGE_FEEDBACK = `${UPDATE_IMAGE_RESULT_INFO_IMAGE_FEEDBACK}`;
</script>
<script type="text/javascript" src="<c:url value='${JS_USER_PROFILE}'/>"></script>
<h1>User Profile</h1>
<div class="content-section">
	<div class="media">
		<jsp:include page="${TEMPLATE_USER_IMAGE_JSP}"/>
		<div class="media-body">
			<h2 id="user-profile-account-login" class="account-heading">${currentUser.login}</h2>
			<p id="user-profile-account-email" class="text-secondary">${currentUser.email}</p>
		</div>
	</div>
	<jsp:include page="${FORM_UPDATE_EMAIL_JSP}"/>
	<jsp:include page="${FORM_UPDATE_LOGIN_JSP}"/>
	<jsp:include page="${FORM_UPDATE_IMAGE_JSP}"/>
	<jsp:include page="${FORM_UPDATE_PASSWORD_JSP}"/>
</div>

