<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

<script>
	var WEB_SITE_NAME = `${WEB_SITE_NAME}`;
	var PROJECT_NAME = `${PROJECT_NAME}`;
	var CONTROLLER = `${CONTROLLER}`;
	var COMMAND = `${COMMAND}`;
	var OPEN_HOME_PAGE = `${OPEN_HOME_PAGE}`;
	var ADD_NEW_ALIEN = `${ADD_NEW_ALIEN}`;
	var ALIEN_NAME = `${ALIEN_NAME}`;
	var ALIEN_SMALL_DESCRIPTION = `${ALIEN_SMALL_DESCRIPTION}`;
	var ALIEN_FULL_DESCRIPTION = `${ALIEN_FULL_DESCRIPTION}`;
	var ALIEN_NEW_IMAGE = `${ALIEN_NEW_IMAGE}`;
	var BAN_USER = `${BAN_USER}`;
	var DAYS_TO_BAN = `${DAYS_TO_BAN}`;
	var UNBAN_USER = `${UNBAN_USER}`;
	var DEMOTE_ADMIN = `${DEMOTE_ADMIN}`;
	var PROMOTE_USER = `${PROMOTE_USER}`;
	var UPDATE_USER_EMAIL = `${UPDATE_USER_EMAIL}`;
	var LOGIN = `${LOGIN}`;
	var NEW_LOGIN = `${NEW_LOGIN}`;
	var PASSWORD = `${PASSWORD}`;
	var PASSWORD_CONFIRM = `${PASSWORD_CONFIRM}`;
	var NEW_IMAGE = `${NEW_IMAGE}`;
	var EMAIL = `${EMAIL}`;
	var NEW_EMAIL = `${NEW_EMAIL}`;
	var USER_ID = `${USER_ID}`;
	var UPDATE_USER_LOGIN = `${UPDATE_USER_LOGIN}`;
	var UPDATE_USER_PASSWORD = `${UPDATE_USER_PASSWORD}`;
	var UPDATE_USER_IMAGE = `${UPDATE_USER_IMAGE}`;

	// users form
	var STANDARD_EMAIL_FEEDBACK = `${STANDARD_EMAIL_FEEDBACK}`;
	var EMAIL_STATUS = `${EMAIL_STATUS}`;
	var EMAIL_FEEDBACK = `${EMAIL_FEEDBACK}`;

	var STANDARD_LOGIN_FEEDBACK = `${STANDARD_LOGIN_FEEDBACK}`;
	var LOGIN_STATUS = `${LOGIN_STATUS}`;
	var LOGIN_FEEDBACK = `${LOGIN_FEEDBACK}`;	

	var STANDARD_PASSWORD_FEDDBACK = `${STANDARD_PASSWORD_FEDDBACK}`;
	var STANDARD_PASSWORD_CONFIRMATION_FEEDBACK = `${STANDARD_PASSWORD_CONFIRMATION_FEEDBACK}`;
	var PASSWORD_STATUS = `${PASSWORD_STATUS}`;
	var PASSWORD_FEEDBACK = `${PASSWORD_FEEDBACK}`;
	var PASSWORD_CONFIRMATION_STATUS = `${PASSWORD_CONFIRMATION_STATUS}`;
	var PASSWORD_CONFIRMATION_FEEDBACK = `${PASSWORD_CONFIRMATION_FEEDBACK}`;
	var PASSWORD_FEEDBACK_INVALID_PASSWORDS_ARE_NOT_EQUAL = `${PASSWORD_FEEDBACK_INVALID_PASSWORDS_ARE_NOT_EQUAL}`;

	var STANDARD_IMAGE_FEEDBACK = `${STANDARD_IMAGE_FEEDBACK}`;
	var IMAGE_FEEDBACK_INVALID = `${IMAGE_FEEDBACK_INVALID}`;
	var IMAGE_STATUS = `${IMAGE_STATUS}`;
	var IMAGE_FEEDBACK = `${IMAGE_FEEDBACK}`;

	var LOGIN_STATUS = `${LOGIN_STATUS}`;
	var DAYS_TO_BAN_STATUS = `${DAYS_TO_BAN_STATUS}`;
	var LOGIN_FEEDBACK = `${LOGIN_FEEDBACK}`;
	var DAYS_TO_BAN_FEEDBACK = `${DAYS_TO_BAN_FEEDBACK}`;
	var STANDARD_LOGIN_FEEDBACK = `${STANDARD_LOGIN_FEEDBACK}`;
	var STANDARD_DAYS_TO_BAN_FEEDBACK = `${STANDARD_DAYS_TO_BAN_FEEDBACK}`;

	var LOGIN_STATUS = `${LOGIN_STATUS}`;
	var LOGIN_FEEDBACK = `${LOGIN_FEEDBACK}`;
	var STANDARD_LOGIN_FEEDBACK = `${STANDARD_LOGIN_FEEDBACK}`;

	var STANDARD_ALIEN_NAME_FEEDBACK = `${STANDARD_ALIEN_NAME_FEEDBACK}`;
	var STANDARD_ALIEN_SMALL_DESCRIPTION_FEEDBACK = `${STANDARD_ALIEN_SMALL_DESCRIPTION_FEEDBACK}`;
	var STANDARD_ALIEN_FULL_DESCRIPTION_FEEDBACK = `${STANDARD_ALIEN_FULL_DESCRIPTION_FEEDBACK}`;
	var STANDARD_IMAGE_FEEDBACK = `${STANDARD_IMAGE_FEEDBACK}`;
	var ALIEN_NAME_STATUS = `${ALIEN_NAME_STATUS}`;
	var ALIEN_SMALL_DESCRIPTION_STATUS = `${ALIEN_SMALL_DESCRIPTION_STATUS}`;
	var ALIEN_FULL_DESCRIPTION_STATUS = `${ALIEN_FULL_DESCRIPTION_STATUS}`;
	var IMAGE_STATUS = `${IMAGE_STATUS}`;
	var ALIEN_NAME_FEEDBACK = `${ALIEN_NAME_FEEDBACK}`;
	var ALIEN_SMALL_DESCRIPTION_FEEDBACK = `${ALIEN_SMALL_DESCRIPTION_FEEDBACK}`;
	var ALIEN_FULL_DESCRIPTION_FEEDBACK = `${ALIEN_FULL_DESCRIPTION_FEEDBACK}`;
	var IMAGE_FEEDBACK = `${IMAGE_FEEDBACK}`;
</script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js'></script>
<script type="text/javascript" src="<c:url value='${JS_USER_PROFILE}'/>"></script>
<script type="text/javascript" src="<c:url value='${JS_ADMIN_PROFILE}'/>"></script>
<h1>${TEXT[TEMPLATE_ADMIN_PROFILE]}</h1>
<div class="content-section">
	<div class="media">
		<jsp:include page="${TEMPLATE_USER_IMAGE_JSP}"/>
		<div class="media-body">
			<h2 id="user-profile-account-login" class="account-heading">${currentUser.login}</h2>
			<p id="user-profile-account-email" class="text-secondary">${currentUser.email}</p>
		</div>
	</div>
	<jsp:include page="${FORM_ALIEN_CREATE_JSP}"/>
	<jsp:include page="${FORM_BAN_UNBAN_USER_JSP}"/>
	<jsp:include page="${FORM_PROMOTE_DEMOTE_JSP}"/>
	<jsp:include page="${FORM_UPDATE_EMAIL_JSP}"/>
	<jsp:include page="${FORM_UPDATE_LOGIN_JSP}"/>
	<jsp:include page="${FORM_UPDATE_IMAGE_JSP}"/>
	<jsp:include page="${FORM_UPDATE_PASSWORD_JSP}"/>
</div>
