package by.shyshaliaksey.webproject.controller.command;

public enum CommandValue {

	REDIRECT_HOME,
	REDIRECT_ABOUT,
	REDIRECT_LOGIN,
	REDIRECT_REGISTER,
	REDIRECT_USER_PROFILE,
	REDIRECT_ALIEN_PROFILE,
	REGISTER_USER,
	LOGIN_USER,
	LOGOUT_USER,
	UPDATE_RATING,
	UPDATE_USER_INFO,
	UPDATE_USER_IMAGE,
	UPDATE_USER_PASSWORD,
	FIND_USER_RATE
	
}
